#!/bin/bash
#
# abinit
#   this script sets up the database with users, database, and seeds it with initial data
#   run this once, first, before running the sql container.
#   then, run this again, as a new container, mounting the container you created with init.
#
set -e

. /usr/local/abin/abenv

sqladm -w ${WEBSOCKET} $@
