#!/bin/bash
#
# abrpc
#
set -e

. /usr/local/etc/abenv

# wait for dependencies, abort after 60 seconds
waitforlink 60
if [ $? -ne 0]
then
  echo 'Link with dependencies failed' >&2
  # i don't know what happens here, maybe the compose tries it again?
  exit 1
fi

sqlauthrpc -w ${WEBSOCKET} $@
